<div class="card mb-3">
    <div class="card-body row">
        <div class="col-md-6">
            @php
                $usersdetails = \DB::table('users')->where('id',$ticket->user_id)->first();
                $departmentInfo = \DB::table('departments')->where('id',$ticket->department_id)->first();
            @endphp
            <p><strong>Generated By</strong> : {{ (isset($u) && $ticket->user_id == $u->id) ? $u->name : (isset($usersdetails->name) ? $usersdetails->name : '-') }}</p>
            <p><strong>Department</strong> : {{ $departmentInfo->name }}</p>
            <p>
                <strong>Status</strong> :
                @if( $ticket->isComplete() && ! $setting->grab('default_close_status_id') )
                    <span style="background-color: green" class="badge text-white">Complete</span>
                @else
                    <span style="background-color: {{ $ticket->status->color }}" class="badge text-white">{{ $ticket->status->name }}</span>
                @endif

            </p>
            <p><strong>Estimate Date</strong> : @if($ticket->estimate_time != null) {{date('d-m-Y', strtotime($ticket->estimate_time))}} @endif</p>

        </div>
        <div class="col-md-6">
            @if($ticket->priority)
                <p>
                    <strong>Priority</strong>:
                    <span style="background-color: {{$ticket->priority->color}}" class="badge text-white">{{$ticket->priority->name}}</span>
                </p>
            @endif
            <p> <strong>Created</strong> : {{ $ticket->created_at->diffForHumans() }}</p>
            <p> <strong>Last Update</strong> : {{ $ticket->updated_at->diffForHumans() }}</p>
        </div>
    </div>
</div>

<div class="card">
    <div class="card-header">
        Ticket Subject
    </div>
    <div class="card-body">
        {!! $ticket->subject !!}
    </div>
</div>

<div class="card mt-3">
    <div class="card-header">
        Ticket Description
    </div>
    <div class="card-body">
        {!! $ticket->html !!}
    </div>
</div>

<div class="card mt-3">
    <div class="card-header">
        Ticket Assigned to
    </div>
    <div class="card-body">
        <table class="table table-bordered table-striped">
            <tbody>
                @foreach (\App\Models\TicketMember::with('user')->where('ticket_id', $ticket->id)->get() as $user)
                <tr>
                    <td> {{ $user->user->name ?? '' }} </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>

{!! CollectiveForm::open([
                'method' => 'DELETE',
                'route' => [
                            $setting->grab('main_route').'.destroy',
                            $ticket->id
                            ],
                'id' => "delete-ticket-$ticket->id"
                ])
!!}
{!! CollectiveForm::close() !!}


@if($u->isAgent() || $u->isAdmin())
    @include('ticket.tickets.edit')
@endif

<div class="modal fade" id="ticket-add-estimatetime" tabindex="-1" role="dialog" aria-labelledby="ticket-add-estimatetime-Label" style="z-index: 9999;">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">

            <div class="modal-header">
                <h5 class="modal-title" id="ticket-add-estimatetime-Label">{{ $ticket->subject }}</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
            </div>
            <div class="modal-body">

                <div class="form-group">
                    <label>Estimate Date <span style="color: red">*</span></label>
                    <input type="text" name="estimate_time" id="estimate_time" class="form-control" placeholder="Select Estimate Date" value="@if($ticket->estimate_time != null) {{date('Y-m-d', strtotime($ticket->estimate_time))}} @endif">
                    <span id="estimate_time_error" class="error" style="color: red"></span>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" name="add_estimatetime" id="add_estimatetime">Save</button>
            </div>
            {!! CollectiveForm::close() !!}
        </div>
    </div>
</div>


{{-- // OR; Modal Window: 2/2 --}}
@if($u->isAdmin())
    @include('ticket.tickets.partials.modal-delete-confirm')
@endif
{{-- // END Modal Window: 2/2 --}}
