<!DOCTYPE html>
<html>
<head>
    <title> {{ APP_NAME }} Merchant Temporary Password</title>
    <link href='https://fonts.googleapis.com/css?family=Open Sans' rel='stylesheet'>
    <style type="text/css">
        .rc_mainWrap{
            min-width: 100%;
            display: block;
            float: left;
            padding: 10px;
            border: #5f0000 10px solid;
            font-family: 'Open Sans';
            line-height: 27px;

        }
        .rc_titleText{
            display: block;
            font-size: 18px;
            font-weight: 700;
            color: #001f3f;
            text-align: center;
        }
        .rc_bodyText{
            padding: 10px 0px;
        }
        .rc_btn{
            display: block;
            text-align: center;
            background: #f39c12;
            padding: 5px;
            color: #000;
            font-weight: 700;
            border-radius: 10px;
        }
        .rc_txtCenter{
            text-align: center;
        }
        .rc_emailLogo{
            width: 30%;
        }
        .rc_emailFooter{
            padding-top: 20px;
            font-size: 12px;
        }
        .rc_box {
            box-sizing: border-box;
            font-family: -apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif,'Apple Color Emoji','Segoe UI Emoji','Segoe UI Symbol';
        }
        .rc_action_button {
            border-radius: 4px;color: #fff;display: inline-block;overflow: hidden;text-decoration: none;background-color: #2d3748;border-bottom: 8px solid #2d3748;border-left: 18px solid #2d3748;border-right: 18px solid #2d3748;border-top: 8px solid #2d3748;
        }
        .work-break-all {
            word-break: break-all;
        }
    </style>
</head>
<body>
    <div class="rc_mainWrap">
        <div class="rc_txtCenter">
            <img class="rc_emailLogo" src="{{ url('assets/logo.webp') }}" border="0" style="height: 70px;width:70px;">
        </div>
        <div class="rc_titleText">
            {{ $subject ?? '' }}
        </div>
        <div class="rc_bodyText">
           
            <hr style="background: #000 !important;">

            <span style="text-align: left;"><b>{{ $ticket_type == 'Add' ? 'Ticket added by' : ($ticket_type == 'Reply' ? 'Ticket reply by' : ($ticket_type == 'Complete' ? 'Ticket complete by' : ($ticket_type == 'Estimate date added' ? 'Estimate date added by' : ($ticket_type == 'Estimate date changed' ? 'Estimate date changed by' : ($ticket_type == 'Reopened' ? 'Ticket reopened by' : '' )) ) ) ) }} : </b> {{ $ticket_added_by ?? '' }} </span><br><br>

            <span style="text-align: left;"><b>Ticket number : </b> {{ $ticket_number ?? '' }} </span><br>

            @if ($ticket_type == 'Reply')

                <span style="text-align: left;"><b>Reply message : </b> {!! (isset($ticket_replay_message) && $ticket_replay_message !=null ? $ticket_replay_message : '') !!} </span><br>
            @endif

            <span style="text-align: left;"><b>Ticket Description : </b> {!! $content !!} </span><br>

            <span style="text-align: left;"><b>Generated By : </b> {{ isset($the_ticket->user) ? ($the_ticket->user->name . ' ' . $the_ticket->user->middle_name . ' ' . $the_ticket->user->last_name) : '' }} </span><br>

            <span style="text-align: left;"><b>Department : </b> {{ $the_ticket->department->name ?? '' }} </span><br>

            <span style="text-align: left;"><b>Status : </b> {{ $the_ticket->status->name ?? '' }} </span><br>

            <span style="text-align: left;"><b>Priority : </b> {{ $the_ticket->priority->name ?? '' }} </span><br>

            <span style="text-align: left;"><b>Estimate Date : </b> {{ !empty($the_ticket->estimate_date) ? date('Y-m-d H:i', strtotime($the_ticket->estimate_date)) : '' }} </span><br>

            <span style="text-align: left;"><b>Created : </b> {{ $the_ticket->created_at->diffForHumans() }} </span><br>

            <span style="text-align: left;"><b>Last Update : </b> {{ $the_ticket->updated_at->diffForHumans() }} </span><br>

        </div>
        <div class="rc_emailFooter">
            <p>Please feel free to contact us at below channels for any questions you have.<br/>
            Best Regards, {{ APP_NAME }} IT Team.</p>
        </div>
    </div>
</body>
</html>